server:
  port: 9090
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wsh0905
    url: jdbc:mysql://localhost:3306/springboot-mybatis?useUnicode=true&characterEncoding=utf-8
#mybatis相关配置
mybatis:
  #指定Mapper.xml文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #执行实体类路径
  type-aliases-package: com.wsh.springboot.springbootmybatis.entity
  #开启控制台打印SQL功能
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
